# Generated by Django 5.1 on 2025-10-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('scraped_html', models.TextField(blank=True, help_text='Raw HTML from Wikipedia', null=True)),
                ('cleaned_text', models.TextField(help_text='Cleaned article text for LLM')),
                ('full_quiz_data', models.TextField(help_text='Complete quiz JSON including questions, entities, and related topics')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-date_generated'],
            },
        ),
    ]
